(add-to-list 'load-path "~/.emacs.d")

(require 'rejeep-paths)

(require 'rejeep-elpa)
(require 'rejeep-ido)
(require 'rejeep-defuns)
(require 'rejeep-bindings)
(require 'rejeep-misc)
(require 'rejeep-osx)

(require 'rejeep-programming)
(require 'rejeep-java)
(require 'rejeep-ruby)
(require 'rejeep-rails)
(require 'rejeep-css)
(require 'rejeep-javascript)
(require 'rejeep-bash)
(require 'rejeep-lisp)
(require 'rejeep-cucumber)
(require 'rejeep-c)
(require 'rejeep-git)

(add-to-list 'load-path "~/Code/html-script-src")
(require 'html-script-src)
