(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(package "coffee-mode")
(package "drag-stuff")
(package "flymake-ruby")
(package "haml-mode")
(package "haskell-mode")
(package "html-script-src")
(package "magit")
(package "magithub")
(package "markdown-mode")
(package "rinari")
(package "rspec-mode")
(package "ruby-end")
(package "ruby-block")
(package "rvm")
(package "sass-mode")
(package "scss-mode")
(package "wrap-region")
(package "yaml-mode")
(package "yasnippet")
(package "ace-jump-mode")
(package "highlight-parentheses")
(package "ruby-tools")
(package "projectile")
(package "helm")
(package "helm-projectile")
(package "expand-region")
(package "popwin")

;; TODO: Not in MELPA yet
(package "color-theme")
(package "highlight-symbol")
(package "htmlize")
(package "jade-mode")
(package "rainbow-mode")
