(custom-set-variables
 '(jde-compiler (quote (("eclipse java compiler server" "/usr/share/eclipse-ecj-3.3/lib/ecj.jar"))))
 '(flymake-allowed-file-name-masks (quote (("\\.java\\'" jde-ecj-server-flymake-init jde-ecj-flymake-cleanup))))
 '(jde-jdk-registry (quote (("1.6" . "/opt/sun-jdk-1.6.0.10"))))
 '(jde-jdk (quote ("1.6")))
 '(jde-global-classpath (quote ("." "/opt/sun-jdk-1.6.0.10/jre/lib/rt.jar")))
 '(jde-complete-function (quote jde-complete-ido))
 '(ecb-options-version "2.32")
 '(truncate-lines t)
 '(openwith-associations (quote (("\\.odt|\\.doc?\\'" "oowriter" (file))
                                 ("\\.pdf\\'" "epdfview" (file))
                                 ("\\.mp3\\'" "mocp" (file))
                                 ("\\.\\(?:mpe?g\\|avi\\|wmv\\|mov\\)\\'" "mplayer" ("-idx" file))
                                 ("\\.\\(?:jp?g\\|png\\)\\'" "xli" (file)))))
 )
(custom-set-faces
 '(flymake-errline ((((class color)) (:underline "OrangeRed"))))
 '(flymake-warnline ((((class color)) (:underline "yellow"))))
 '(yas/field-highlight-face ((t (:background "green" :foreground "black"))))
 '(yas/mirror-highlight-face ((t nil)))
 )