(defun move-region-to-scratch-buffer()
  "Moves region to *scratch* buffer."
  (interactive)
  (let ((prev-buffer (buffer-name)))    
    (kill-region (point) (mark))
    (switch-to-buffer "*scratch*")
    (end-of-buffer)
    (yank)
    (insert "\n")
    (switch-to-buffer prev-buffer)))